name: mobsfscan

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  mobsfscan:
    runs-on: ubuntu-latest
    name: mobsfscan code scanning
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --json --output results.json --no-fail'

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mobsfscan-report
          path: results.json